### ISSUE TITLE
А тесты?

### ISSUE THREAD

**Issue by dankondr** [onewhosaynope/1000listnick#1]
Покройте тестами, потом окупится)

**Comment by jag-k** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Оценить CodeStream](https://trello.com/c/wXYFXo7R/1-%D0%BE%D1%86%D0%B5%D0%BD%D0%B8%D1%82%D1%8C-codestream)

**Comment by jag-k** [comment]
Hmmm.... Not now
